### ISSUE TITLE
Unhandled Exception: System.ArgumentOutOfRangeException: Length cannot be less than zero.

### ISSUE THREAD

**Issue by akankshaaSaba** [NivNavick/trxer#11]
trx created on VS2013

C:\covertedFiles>"C:\Program Files (x86)\trx2html\TrxerConsole.exe" testResults1.trx
Trx File
testResults1.trx
Loading xslt template...
Loading css...
Loading javascript...
Transforming...

Unhandled Exception: System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at System.Xml.Xsl.CompiledQuery.Script1.RemoveAssemblyName(String asm)
   at System.Xml.Xsl.CompiledQuery.Query.<xsl:template name="compiler:generated"> (6)(XmlQueryRuntime {urn:schemas-microsoft-com:xslt-debug}runtime, XPathNavigator {urn:schemas-microsoft-com:
xslt-debug}last, IList`1 {urn:schemas-microsoft-com:xslt-debug}namespaces, IList`1 testRunOutcome, IList`1 testsFailedSet, IList`1 testsFailedCount, IList`1 classSet, IList`1 classCount)
   at System.Xml.Xsl.CompiledQuery.Query.<xsl:template name="compiler:generated"> (4)(XmlQueryRuntime {urn:schemas-microsoft-com:xslt-debug}runtime, XPathNavigator {urn:schemas-microsoft-com:
xslt-debug}last, IList`1 {urn:schemas-microsoft-com:xslt-debug}namespaces, IList`1 classCount, IList`1 classSet, IList`1 testsFailedCount, IList`1 testsFailedSet, IList`1 testRunOutcome)
   at System.Xml.Xsl.CompiledQuery.Query.<xsl:template name="compiler:generated"> (3)(XmlQueryRuntime {urn:schemas-microsoft-com:xslt-debug}runtime, XPathNavigator {urn:schemas-microsoft-com:
xslt-debug}last, IList`1 {urn:schemas-microsoft-com:xslt-debug}namespaces, IList`1 testRunOutcome)
   at System.Xml.Xsl.CompiledQuery.Query.<xsl:template name="compiler:generated"> (2)(XmlQueryRuntime {urn:schemas-microsoft-com:xslt-debug}runtime, XPathNavigator {urn:schemas-microsoft-com:
xslt-debug}last, IList`1 {urn:schemas-microsoft-com:xslt-debug}namespaces, IList`1 testRunOutcome)
   at System.Xml.Xsl.CompiledQuery.Query.<xsl:template match="/">(XmlQueryRuntime {urn:schemas-microsoft-com:xslt-debug}runtime, XPathNavigator {urn:schemas-microsoft-com:xslt-debug}current,
st`1 {urn:schemas-microsoft-com:xslt-debug}namespaces)
   at System.Xml.Xsl.CompiledQuery.Query.<xsl:apply-templates>(XmlQueryRuntime {urn:schemas-microsoft-com:xslt-debug}runtime, XPathNavigator , Double , Double )
   at System.Xml.Xsl.CompiledQuery.Query.Root(XmlQueryRuntime {urn:schemas-microsoft-com:xslt-debug}runtime)
   at System.Xml.Xsl.CompiledQuery.Query.Execute(XmlQueryRuntime {urn:schemas-microsoft-com:xslt-debug}runtime)
   at System.Xml.Xsl.XmlILCommand.Execute(Object defaultDocument, XmlResolver dataSources, XsltArgumentList argumentList, XmlSequenceWriter results)
   at System.Xml.Xsl.XmlILCommand.Execute(Object defaultDocument, XmlResolver dataSources, XsltArgumentList argumentList, XmlWriter writer)
   at System.Xml.Xsl.XslCompiledTransform.Transform(String inputUri, String resultsFile)
   at TrxerConsole.Program.Transform(String fileName, XmlDocument xsl)
   at TrxerConsole.Program.Main(String[] args)

**Comment by Menur** [comment]
HI can you publish your .trx file which causes exception, i had also problem with 2013 VS #10

**Comment by akankshaaSaba** [comment]
PFA..

**Comment by DMApplications** [comment]
I had the same issue. The problem is in the RemoveAssemblyName function. asm.IndexOf(',') returns -1 and this is invalid parameter for the Substring function.

**Comment by sthirion** [comment]
In the Trxer.xslt, try changing the method RemoveAssemblyName (on line 13) to:
public string RemoveAssemblyName(string asm) 
{
  if(asm.IndexOf(',')>0) {
    return asm.Substring(0,asm.IndexOf(','));
  } else {return asm;}
}
