### ISSUE TITLE
Visual Studio 2019 

### ISSUE THREAD

**Issue by quebez** [NivNavick/trxer#42]
I tried parsing unit test from Visual Studio 2019 Community and it doesn't work. I ran the tests using command: `vstest.console.exe xxx.dll /logger:trx`
from console:
```
Loading xslt template...
Loading css...
Loading javascript...
Transforming...

Unhandled Exception: System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at System.Xml.Xsl.CompiledQuery.Script1.RemoveAssemblyName(String asm) in c:\Users\xxx\AppData\Local\Temp\d1xp0pdy.0.cs:line 29
```

This is from .trx file where I guess it failed.
From .trx which failed: 
```
<UnitTest name="xxx" storage="c:\xxx" id="xxx">
      <Execution id="xxx" />
      <TestMethod codeBase="c:\xxx" adapterTypeName="executor://mstestadapter/v2" className="xxx.xxx" name="xxx" />
    </UnitTest>
```
From .trx which passed (your example): 
```
<UnitTest name="WarnTest" storage="c:\users\nivnavick\desktop\prologwin\prolog\prologgertests\bin\release\prologgertests.dll" id="5e3cd15a-aba7-333e-80af-38c992a98a19">
      <Execution id="e62eeea5-984e-4eb1-87a5-22c4fec39062" />
      <TestMethod codeBase="C:/Users/NivNavick/Desktop/ProLogWin/ProLog/ProLoggerTests/bin/Release/ProLoggerTests.DLL" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="ProLoggerTests.UnitTest1, ProLoggerTests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" name="WarnTest" />
    </UnitTest>
```

Also, when I fix it, it throws another exception. It would be great to catch these and just log them and add N/A in HTML || ignoring the exception would work as well.
```
Unhandled Exception: System.FormatException: String was not recognized as a valid TimeSpan.
   at System.Globalization.TimeSpanParse.TimeSpanResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument, String failureArgumentName)
   at System.Globalization.TimeSpanParse.TryParseTimeSpan(String input, TimeSpanStandardStyles style, IFormatProvider formatProvider, TimeSpanResult& result)
   at System.Globalization.TimeSpanParse.Parse(String input, IFormatProvider formatProvider)
   at System.TimeSpan.Parse(String s)
```

**Comment by quebez** [comment]
Building the project and using the generated .exe file solves the issue.
